# Generated by Django 4.2.7 on 2025-01-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myblogapp', '0002_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
